# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_post(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.LINK_TEXT, "New Article").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control-lg").send_keys("Title")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys("About me")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control").send_keys("Writing")
    self.driver.find_element(By.CSS_SELECTOR, ".ti-new-tag-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ti-new-tag-input").send_keys("me")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
