# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestRegistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registration(self):
    self.driver.get("http://localhost:1667/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) > .form-control").send_keys("tesztike")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) > .form-control").send_keys("tesztike@teszt.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) > .form-control").send_keys("Abcdef123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swal-button").click()
  
