on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Start conduit
        run: |
          docker-compose up -d
     
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
           
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner
          
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
          
      - name: Install seleniumbase
        run: pip install seleniumbase
 
      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
      
     
      - name: Run tests
        continue-on-error: true
        run: |
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/registration.side
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/login.side
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/post.side
