on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Builds and Starts
        run: |
          docker-compose up -d
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner
          
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
          
      - name: Install seleniumbase
        run: pip install seleniumbase

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver
      - name: Run tests
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/registration.side
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/login.side
         selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/post.side
         
      - name: Run Tests
        run: |
          pytest --alluredir=allure-results
      
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages    
          
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
         allure_results: allure-results
         allure_history: allure-history
         keep_reports: 20
        
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: allure-history
